openapi: 3.0.3
info:
  title: Richard Werner Payment Lists Backend - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:7066/api

paths: 
  /users:
    get:
      summary: summary
      description: description
      tags: [users]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
  /payment-contexts:
    get:
      summary: get a list of available payment contexts
      description: get a list of available payment contexts
      tags: [payment-context]
      responses: 
        '200':
          description: Successful operation
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentContextsResponse'
  /paymentContext/{paymentContext}/payments:
    get: 
      summary: get a list of payments
      description: get a list of payments
      tags: [payments]
      parameters:
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentsResponse'
    post:
      summary: post a new payment
      description: post a new payment
      tags: [payments]
      parameters:
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      requestBody:
        description: the payment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPaymentRequest'
      responses:
        '200':
          description: Created
  /paymentContext/{paymentContext}/payments/{paymentId}:
    get: 
      summary: get a payment by its id
      description: get a payment by its id
      tags: [payments]
      parameters:
        - in: path
          name: paymentId
          schema: 
            type: number
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentsByIdResponse'  
    delete:
      summary: invalidates a payment by its id. It wont be included in any calculations
      description: invalidates a payment. It wont be included in any calculations
      tags: [payments]
      parameters:
        - in: path
          name: paymentId
          schema: 
            type: number
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Success
  /paymentContext/{paymentContext}/payments-for-debitor/{username}:
    get:
      summary: get a list of payments where the user is a debitor 
      description: get a list of payments where the user is a debitor 
      tags: [payments]
      parameters:
        - in: path
          name: username
          schema: 
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentsForDebitorResponse'
  /paymentContext/{paymentContext}/payments-for-creditor/{username}:
    get:
      summary: get a list of payments where the user is the creditor 
      description: get a list of payments where the user is the creditor
      tags: [payments]
      parameters:
        - in: path
          name: username
          schema: 
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentsForCreditorResponse'
  /paymentContext/{paymentContext}/payments-for-author/{username}:
    get:
      summary: get a list of payments where the user is the author 
      description: get a list of payments where the user is the author
      tags: [payments]
      parameters:
        - in: path
          name: username
          schema: 
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentsForAuthorResponse'
  /paymentContext/{paymentContext}/payment-overview-for-debitor/{username}:
    get:
      summary: get an overview of payments where the user is a debitor 
      description: get an overview of payments where the user is a debitor 
      tags: [payment overview]
      parameters:
        - in: path
          name: username
          schema: 
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentOverviewForDebitorResponse'
  /paymentContext/{paymentContext}/payment-overview-for-creditor/{username}:
    get:
      summary: get an overview of payments where the user is the creditor 
      description: get an overview of payments where the user is the creditor
      tags: [payment overview]
      parameters:
        - in: path
          name: username
          schema: 
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GetPaymentOverviewForCreditorResponse'
  /paymentContext/{paymentContext}/bills:
    get:
      summary: get a list of bills
      description: get a list of bills
      tags: [bills]
      parameters:
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllBillsResponse'
  /paymentContext/{paymentContext}/bills/all/users/{username}:
    get:
      summary: get a list of bills for a user
      description: get a list of bills for a user
      tags: [bills]
      parameters:
        - in: path
          name: username
          description: username of the user
          schema:
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillsForUserResponse'
                
  /paymentContext/{paymentContext}/bill-overviews:
    get:
      summary: get an overview of bills for all users
      description: get an overview of bills for all users
      tags: [bill overview]
      parameters:
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllBillOverviewsResponse'                
  /paymentContext/{paymentContext}/bill-overviews/all/users/{username}:
    get:
      summary: get an overview of bills for a user
      description: get an overview of bills for a user
      tags: [bill overview]
      parameters:
        - in: path
          name: username
          description: username of the user
          schema:
            type: string
          required: true
        - in: path
          name: paymentContext
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillOverviewsForUserResponse'
components:
  schemas:
    GetUsersResponse:
      type: object
      properties:
        userList:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - userList
    GetPaymentContextsResponse:
      type: object
      properties: 
        paymentContexts:
          type: array
          items:
            $ref: '#/components/schemas/PaymentContext'     

    GetPaymentsResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
      required: 
        - payments
    PostPaymentRequest:
      type: object
      properties: 
        payment:
          $ref: '#/components/schemas/PostPayment'
      required: 
        - payment
    GetPaymentsByIdResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
    
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: name123
        firstName:
          type: string
          example: hlaskjdha
        lastName:
          type: string
          example: lkajsdhö
      required: 
        - id
        - username
        - firstName
        - lastName
    Payment:
      type: object
      properties:
        paymentId: 
          type: integer
          format: int64
          example: 42
          description: resource id of the payment
        paymentDescription: 
          type: string
          example: 'dinner at mcDonalds'
        paymentDate:
          type: string
          description: date of the payment
          format: date-time
          example: '2024-01-04'
        price: 
          type: number
          example: 20.99
        debitors:
          type: array
          example: ['name123', 'name234']
          items: 
            type: string
            example: 'name123'
        creditor:
          type: string
          example: 'name123'
        author:
          type: string
          example: 'name123'
        updateTime:
          type: string
          format: date-time
      required:
        - paymentId
        - paymentDescription
        - paymentDate
        - price
        - debitors
        - creditor
        - author
        - updateTime
    PaymentContext:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name: 
          type: string
          example: "Tscheschien_2024"
        isClosed: 
          type: boolean
          example: true
      required:
        - id
        - name
        - isClosed
    PostPayment:
      type: object
      properties:
        paymentDescription: 
          type: string
          example: 'dinner at mcDonalds'
        paymentDate:
          type: string
          description: date of the payment
          format: date-time
          example: '2024-01-04'
        price: 
          type: number
          example: 20.99
        debitors:
          type: array
          example: ['name234', 'name123']
          items: 
            type: string
            example: 'name123'
        creditor:
          type: string
          example: 'name123'
        author:
          type: string
          description: username of the user who created this payment
      required:
        - paymentDescription
        - paymentDate
        - price
        - debitors
        - creditor
        - author
        
    GetPaymentsForDebitorResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
      required: 
        - payments
    GetPaymentsForCreditorResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
      required: 
        - payments
    GetPaymentsForAuthorResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
      required: 
        - payments
        
    GetPaymentOverviewForDebitorResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
        calculationTime:
          type: string
          description: date of the calculation
          format: date-time
          example: '2024-01-04'
        totalDebitorOnly:
          type: number
          example: 24.42
      required: 
        - payments
        - calculationTime
        - totalDebitorOnly
    GetPaymentOverviewForCreditorResponse:
      type: object
      properties: 
        payments:
          type: array
          items: 
            $ref: '#/components/schemas/Payment'
        calculationTime:
          type: string
          description: date of the calculation
          format: date-time
          example: '2024-01-04'
        totalWithCreditor:
          type: number
          example: 169.42
        totalWithoutCreditor:
          type: number
          example: 159.32
      required: 
        - payments
        - calculationTime
        - totalWithCreditor
        - totalWithoutCreditor
        
    GetAllBillsResponse:
      type: object
      properties:
        calculationTime:
          type: string
          format: date-time
          example: "2024-06-28T22:13:13.965Z"  
        bills:
          type: array
          items:
            $ref: '#/components/schemas/Bill'
      required:
        - bills
        - calculationTime
    GetBillsForUserResponse:
      type: object
      properties:
        calculationTime:
          type: string
          format: date-time
          example: "2024-06-28T22:13:13.965Z"  
        bills:
          type: array
          items:
            $ref: '#/components/schemas/Bill'
      required:
        - bills
        - calculationTime
        
    GetAllBillOverviewsResponse:
      type: object
      properties:
        calculationTime:
          type: string
          format: date-time
          example: "2024-06-28T22:13:13.965Z"  
        bills:
          type: array
          items:
            $ref: '#/components/schemas/ShortBill'
      required:
        - bills
        - calculationTime
        
    GetBillOverviewsForUserResponse:
      type: object
      properties:
        calculationTime:
          type: string
          format: date-time
          example: "2024-06-28T22:13:13.965Z"  
        bills:
          type: array
          items:
            $ref: '#/components/schemas/ShortBill'
        balance:
          type: number
          description: balance of the user over all bills. Positive -> you get money back. Negative -> you have to pay a lot 
      required:
        - bills
        - calculationTime
        - balance
    Bill:
      type: object
      properties:
        issuedBy:
          type: string
          description: receiver of the money issued with this bill
          example: 'name123'
        issuedFor:
          type: string
          description: receiver of the money issued with this bill
          example: 'name123'
        amount: 
          type: number
          description: amount of money that needs to be transfered to the receiver of the bill
          example: 42.69
        billComposites:
          type: array
          items: 
            $ref: '#/components/schemas/BillComposite'
      required:
        - issuedBy
        - issuedFor
        - amount
        - billComposites
    ShortBill:
      type: object
      properties:
        issuedBy:
          type: string
          description: receiver of the money issued with this bill
          example: 'name123'
        issuedFor:
          type: string
          description: receiver of the money issued with this bill
          example: 'name123'
        amount: 
          type: number
          description: amount of money that needs to be transfered to the receiver of the bill
          example: 42.69
      required:
        - issuedBy
        - issuedFor
        - amount
    BillComposite: 
      type: object
      properties:
        amount:
          type: number
          description: portion of the payment price the user issuedFor has to pay to issuedBy 
        payment:
          $ref: '#/components/schemas/Payment'
      required:
        - amount
        - payment
        